-- MySQL Script generated by MySQL Workbench
-- Fri 29 Apr 2016 06:33:58 PM AKDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema push_notifications
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema push_notifications
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `push_notifications` DEFAULT CHARACTER SET latin1 ;
USE `push_notifications` ;

-- -----------------------------------------------------
-- Table `push_notifications`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `push_notifications`.`clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(4) NOT NULL,
  `token` TEXT NOT NULL,
  `kpTrigger` CHAR(1) NOT NULL DEFAULT '6',
  `latitude` DECIMAL(10,5) NULL DEFAULT '0',
  `longitude` DECIMAL(10,5) NULL DEFAULT '0',
  `notify_start_time` TIME NULL DEFAULT '00:00:00',
  `notify_stop_time` TIME NULL DEFAULT '23:59:59',
  `is_active` CHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
